'use client'

import { Bell, Clock3, Lightbulb, SlidersHorizontal } from 'lucide-react'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'
import { Switch } from '@/components/ui/switch'
import { cn } from '@/lib/utils'
import type { Chronotype, SettingsData } from '@/components/lumisync-app'

export function SettingsScreen({ chronotype, settings, onChronotypeChange, onSettingsChange }: { chronotype: Chronotype; settings: SettingsData; onChronotypeChange: (chronotype: Chronotype) => void; onSettingsChange: (settings: SettingsData) => void }) {
  const update = (patch: Partial<SettingsData>) => onSettingsChange({ ...settings, ...patch })
  return <section className="flex flex-col gap-5" aria-labelledby="settings-title"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-primary">Preferences</p><h1 id="settings-title" className="mt-1 text-2xl font-semibold tracking-tight">Settings</h1></div><Accordion multiple defaultValue={['chronotype']} className="gap-3">
    <AccordionItem value="chronotype" className="rounded-2xl bg-card px-4 ring-1 ring-border"><AccordionTrigger className="py-4 hover:no-underline"><span className="flex items-center gap-3"><Clock3 className="size-4 text-primary" /> User Chronotype</span></AccordionTrigger><AccordionContent className="flex flex-col gap-4 pb-4"><div className="grid grid-cols-2 gap-3"><label className="flex flex-col gap-2 text-xs text-muted-foreground">Wake<input type="time" value={settings.wakeTime} onChange={(event) => update({ wakeTime: event.target.value })} className="rounded-lg border border-border bg-background px-3 py-2 font-mono text-sm text-foreground" /></label><label className="flex flex-col gap-2 text-xs text-muted-foreground">Sleep<input type="time" value={settings.sleepTime} onChange={(event) => update({ sleepTime: event.target.value })} className="rounded-lg border border-border bg-background px-3 py-2 font-mono text-sm text-foreground" /></label></div><div><p className="mb-2 text-xs text-muted-foreground">Rhythm type</p><div className="grid grid-cols-3 gap-2">{(['Morning Lark','Intermediate','Night Owl'] as Chronotype[]).map((item) => <button key={item} onClick={() => onChronotypeChange(item)} aria-pressed={chronotype === item} className={cn('rounded-lg border px-2 py-2 text-xs leading-tight', chronotype === item ? 'border-primary bg-primary/10 text-primary shadow-[0_0_12px_var(--glow-primary)]' : 'border-border text-muted-foreground')}>{item}</button>)}</div></div></AccordionContent></AccordionItem>
    <AccordionItem value="intensity" className="rounded-2xl bg-card px-4 ring-1 ring-border"><AccordionTrigger className="py-4 hover:no-underline"><span className="flex items-center gap-3"><SlidersHorizontal className="size-4 text-primary" /> Task Intensity</span></AccordionTrigger><AccordionContent className="flex flex-col gap-5 pb-4"><label className="flex flex-col gap-3 text-xs"><span className="flex justify-between"><span>High-focus threshold</span><output className="font-mono text-primary">{settings.high}%</output></span><input type="range" value={settings.high} onChange={(event) => update({ high: Number(event.target.value) })} min="0" max="100" className="native-lumi-slider" /></label><label className="flex flex-col gap-3 text-xs"><span className="flex justify-between"><span>Low-focus threshold</span><output className="font-mono text-accent">{settings.low}%</output></span><input type="range" value={settings.low} onChange={(event) => update({ low: Number(event.target.value) })} min="0" max="100" className="native-lumi-slider" /></label></AccordionContent></AccordionItem>
    <AccordionItem value="hardware" className="rounded-2xl bg-card px-4 ring-1 ring-border"><AccordionTrigger className="py-4 hover:no-underline"><span className="flex items-center gap-3"><Lightbulb className="size-4 text-primary" /> Hardware Integrations</span></AccordionTrigger><AccordionContent className="pb-4"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium">Govee Strip</p><p className="mt-1 flex items-center gap-2 text-xs text-muted-foreground"><span className={cn('size-1.5 rounded-full', settings.govee ? 'bg-primary shadow-[0_0_6px_var(--primary)]' : 'bg-muted-foreground')} /> {settings.govee ? 'Online' : 'Offline'}</p></div><Switch checked={settings.govee} onCheckedChange={(govee) => update({ govee })} /></div></AccordionContent></AccordionItem>
    <AccordionItem value="notifications" className="rounded-2xl bg-card px-4 ring-1 ring-border"><AccordionTrigger className="py-4 hover:no-underline"><span className="flex items-center gap-3"><Bell className="size-4 text-primary" /> Notifications</span></AccordionTrigger><AccordionContent className="flex flex-col gap-4 pb-4"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium">Push alerts</p><p className="mt-1 text-xs text-muted-foreground">Light plan reminders</p></div><Switch checked={settings.push} onCheckedChange={(push) => update({ push })} /></div><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium">Wind-down warnings</p><p className="mt-1 text-xs text-muted-foreground">30 minutes before sleep</p></div><Switch checked={settings.windDown} onCheckedChange={(windDown) => update({ windDown })} /></div></AccordionContent></AccordionItem>
  </Accordion></section>
}
